auto:	          true
markdown:         rdiscount
pygments:         true
paginate:         10
permalink:        /blog/:year:month/:title.html

title:            II-Matto
url:              http://ii-matto.github.com/

author:
    name:         II-Matto
    sina_weibo:	  http://weibo.com/ptsntwsz
    
description:      "II-Matto\'s Blog"
author_info:      <a href="http://ii-matto.github.com/about">II-Matto</a>

copyright:
    - Design by <a href="http://ii-matto.github.com/about" title="II-Matto" target="_blank">II-Matto</a> &copy; 2013
