timezone:      Asia/Shanghai
encoding:      utf-8
permalink:     /blog/:year:month:day/:title.html

paginate:      7
paginate_path: "blog/page:num/"

highlighter:   pygments

sass:
    sass_dir: _sass
    style:    :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!-- End of Excerpt -->"
  -
    scope:
      path: "projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "project" # overrides previous default layout
      author: "Mr. Hyde"
