timezone:          Asia/Shanghai
encoding:          utf-8
permalink:         /blog/:year:month:day/:title.html

paginate:          7
paginate_path:     "blog/page:num/"

highlighter:       pygments

excerpt_separator: "<!-- End of Excerpt -->"

exclude:           [bak/, Gemfile, Gemfile.lock, README.textile]

sass:
    sass_dir: _sass
    style:    :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "project" # overrides previous default layout
      author: "Mr. Hyde"